# -*- coding: utf-8 -*-
"""Deep_Q_Learning_for_Lunar_Landing_Complete_Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y6sCgwr-E0J6c5Ti_7SeYLTxd4pDiUvd

# Deep Q-Learning for Lunar Landing

## Part 0 - Installing the required packages and importing the libraries

### Installing Gymnasium
"""

!pip install gymnasium
!pip install "gymnasium[atari, accept-rom-license]"
!apt-get install -y swig
!pip install gymnasium[box2d]

"""### Importing the libraries"""

import os
import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torch.autograd as autograd
from torch.autograd import Variable
from collections import deque, namedtuple

"""## Part 1 - Building the AI

### Creating the architecture of the Neural Network
"""

class Network(nn.Module):
  def __init__(self, state_size, action_size, seed=42):
    super(Network, self).__init__()   #inheritance using super
    self.seed = torch.manual_seed(seed)
    self.fc1 = nn.Linear(state_size, 64)    #creating our 3 fc layers
    self.fc2 = nn.Linear(64, 64)
    self.fc3 = nn.Linear(64, action_size)
  def forward(self, state):
    x = self.fc1(state)         # sending input to the 1st fully connected layer
    x = F.relu(x)               # w the help of rectifier activating unit
    x = self.fc2(x)
    x = F.relu(x)
    return  self.fc3(x)

"""## Part 2 - Training the AI

### Setting up the environment
"""

import gymnasium as gym
env = gym.make('LunarLander-v2')
state_shape = env.observation_space.shape #ref to the vector of 8 elements (8,)
state_size = env.observation_space.shape[0] #ref to the 8 state coord post coord, vel coord etc
number_actions = env.action_space.n #ref to the 4 actions
print('State shape: ', state_shape)
print('State size: ', state_size)
print('Number of actions: ', number_actions)

"""### Initializing the hyperparameters"""

learning_rate = 5e-4
minibatch_size = 100 #no of obs used to update the model
discount_factor = 0.99
replay_buffer_size = int(1e5) #memory of the agent
interpolation_parameter = 1e-3

"""### Implementing Experience Replay"""

class ReplayMemory(object):

  def __init__(self, capacity):
    self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu") #code if we want to execute the code with a gpu for faster performance
    self.capacity = capacity
    self.memory = []

  def push(self, event): #used to add an event into the memory buffer
    self.memory.append(event) #appeding the memory w the event
    if len(self.memory) > self.capacity: #checking if we have exceeded size of buffer
      del self.memory[0] #if so deleting the oldest event

  def sample(self, batch_size): #rand select a batch of experiences from obj
    experiences = random.sample(self.memory, k = batch_size)
    #stacking all the states, actions & rewards
    states = torch.from_numpy(np.vstack([e[0] for e in experiences if e is not None])).float().to(self.device)
    actions = torch.from_numpy(np.vstack([e[1] for e in experiences if e is not None])).long().to(self.device) #actions will not be float vals
    rewards = torch.from_numpy(np.vstack([e[2] for e in experiences if e is not None])).float().to(self.device) #rewards will be float vals
    next_states = torch.from_numpy(np.vstack([e[3] for e in experiences if e is not None])).float().to(self.device)
    dones = torch.from_numpy(np.vstack([e[4] for e in experiences if e is not None]).astype(np.uint8)).float().to(self.device) #last element of experience, 'uint8' is used to repr bool values b4 cov then into float
    return states, next_states, actions, rewards, dones

"""### Implementing the DQN class"""

class Agent():

  def __init__(self, state_size, action_size):
    self.device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    self.state_size = state_size
    self.action_size = action_size
    self.local_qnetwork = Network(state_size, action_size).to(self.device)
    self.target_qnetwork = Network(state_size, action_size).to(self.device)
    self.optimizer = optim.Adam(self.local_qnetwork.parameters(), lr = learning_rate)
    self.memory = ReplayMemory(replay_buffer_size)
    self.t_step = 0

  def step(self, state, action, reward, next_state, done):
    self.memory.push((state, action, reward, next_state, done)) #storig the exp in replay memory
    self.t_step = (self.t_step + 1) % 4 #icrem time step and resetting at every 4 step
    if self.t_step == 0: #the learning part on every 4 time steps
      if len(self.memory.memory) > minibatch_size:
        experiences = self.memory.sample(100) #sampling 100 samples
        self.learn(experiences, discount_factor)

  def act(self, state, epsilon = 0.):
   state = torch.from_numpy(state).float().unsqueeze(0) #adding a new dimension in the beginning of the sample which tells us its batch
   self.local_qnetwork.eval() #setting the model to eval mode
   with torch.no_grad():  #going from training mode to inference mode to predict our values
    action_values = self.local_qnetwork(state)
   self.local_qnetwork.train() #setting our loc qnetwork back to training mode
   if random.random() > epsilon:
    return np.argmax(action_values.cpu().data.numpy()) #now implementing epsilon greedy method where a rand value will be generated and
   else:                                               # if the val is greater than epsilon, the highest q factor will be seleceted
    return random.choice(np.arange(self.action_size))  # if less then random q value is selected
  def learn(self, experiences, discount_factor):
    states, next_states, actions, rewards, dones = experiences
    next_q_targets = self.target_qnetwork(next_states).detach().max(1)[0].unsqueeze(1) #calculating the followig q targets
    q_targets = rewards + discount_factor * next_q_targets * (1 - dones) #calculating current
    q_expected = self.local_qnetwork(states).gather(1, actions) #calculating current value
    loss = F.mse_loss(q_expected, q_targets) #calculating mean square error loss
    self.optimizer.zero_grad()
    loss.backward() # back proporgation to update the parameters
    self.optimizer.step() #performs a single step to update the model parameter
    self.soft_update(self.local_qnetwork, self.target_qnetwork, interpolation_parameter)

  def soft_update(self, local_model, target_model, interpolation_parameter):
    for target_param, local_param in zip(target_model.parameters(), local_model.parameters()):
      target_param.data.copy_(interpolation_parameter * local_param.data + (1.0 - interpolation_parameter) * target_param.data)

"""### Initializing the DQN agent"""

agent = Agent(state_size, number_actions)

"""### Training the DQN agent"""

number_episodes = 2000
maximum_number_timesteps_per_episode = 1000
epsilon_starting_value  = 1.0
epsilon_ending_value  = 0.01
epsilon_decay_value  = 0.995
epsilon = epsilon_starting_value
scores_on_100_episodes = deque(maxlen = 100)

for episode in range(1, number_episodes + 1):
  state, _ = env.reset() #not only do we gwt the state after resettig but we also get some addit. info which is give in _
  score = 0
  for t in range(maximum_number_timesteps_per_episode): #iteration of timesteps
    action = agent.act(state, epsilon) #here we're implementing act fn to get our action value in e greedy
    next_state, reward, done, _, _ = env.step(action) #fetching the char of the state from the environment
    agent.step(state, action, reward, next_state, done) #herr the step fn is impl learn fn which is thus making the nn learn
    state = next_state
    score += reward
    if done:
      break
  scores_on_100_episodes.append(score)
  epsilon = max(epsilon_ending_value, epsilon * epsilon_decay_value)
  print('\rEpisodes {}\tAverage score {:.2f}'.format(episode, np.mean(scores_on_100_episodes)), end="")
  if episode % 100 == 0:
    print('\rEpisodes {}\tAverage score {:.2f}'.format(episode, np.mean(scores_on_100_episodes)))
  if np.mean(scores_on_100_episodes)>=200:
    print('\nEnvironment solved in {} episodes Average score {} Congratulations!'.format(episode, np.mean(scores_on_100_episodes)))
    torch.save(agent.local_qnetwork.state_dict(), 'checkpoint.pth')
    break

"""## Part 3 - Visualizing the results"""

import glob
import io
import base64
import imageio
from IPython.display import HTML, display
from gym.wrappers.monitoring.video_recorder import VideoRecorder

def show_video_of_model(agent, env_name):
    env = gym.make(env_name, render_mode='rgb_array')
    state, _ = env.reset()
    done = False
    frames = []
    while not done:
        frame = env.render()
        frames.append(frame)
        action = agent.act(state)
        state, reward, done, _, _ = env.step(action.item())
    env.close()
    imageio.mimsave('video.mp4', frames, fps=30)

show_video_of_model(agent, 'LunarLander-v2')

def show_video():
    mp4list = glob.glob('*.mp4')
    if len(mp4list) > 0:
        mp4 = mp4list[0]
        video = io.open(mp4, 'r+b').read()
        encoded = base64.b64encode(video)
        display(HTML(data='''<video alt="test" autoplay
                loop controls style="height: 400px;">
                <source src="data:video/mp4;base64,{0}" type="video/mp4" />
             </video>'''.format(encoded.decode('ascii'))))
    else:
        print("Could not find video")

show_video()

